name: Quality tester

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Greetings
      run: echo "Hello!"
    - name: Run evaluation
      run: make evaluate
