name: Quality tester

on:
  push:
    paths:
      - 'src/*'
      - 'client/*'
      - 'data/check/*'
      - 'metadata.json'
      - 'Makefile'
      - 'models/*'
      - 'models/data/*'
      - 'models/data/dictionaries/*'

jobs:
  evaluate:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Evaluation
      run: make evaluate
    - name: Metrics by ID
      run: cat client/reports/$(ls -1 client/reports/ | tail -n 1)/metrics_by_id.csv
    - name: Metrics by Exam
      run: cat client/reports/$(ls -1 client/reports/ | tail -n 1)/metrics_by_exam.csv
    - name: Upload Artifacts to Storage
      run: |
        echo ${DASH_SSH_KEY} > ~/.ssh/id_rsa_dash
        scp -i ~/.ssh/id_rsa_dash client/reports/$(ls -1 client/reports/ | tail -n 1)/metrics_by_id.csv cloud-user@23.111.106.99:/home/cloud-user/shared/ai-journey-2019/scores_dir/${git rev-parse HEAD}.csv
