name: Quality tester

on:
  push:
#    paths:
#      - 'src/*'
#      - 'client/*'
#      - 'data/check/*'
#      - 'metadata.json'
#      - 'Makefile'
#      - 'models/*'
#      - 'models/data/*'
#      - 'models/data/dictionaries/*'

jobs:
  evaluate:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Send code to server
      env:
        EVAL_SSH_KEY: ${{ secrets.DASH_SSH_KEY }}
      run: |
        echo "$EVAL_SSH_KEY" > ~/id_rsa_eval
        chmod 400 ~/id_rsa_eval
        cd .. && tar -cvzf code.tar.gz ai-journey-2019 && cd ai-journey-2019
        scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/id_rsa_eval ../code.tar.gz cloud-user@23.111.106.99:/home/cloud-user/eval_server/${GITHUB_SHA}.tar.gz
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/id_rsa_eval cloud-user@23.111.106.99 "cd /home/cloud-user/eval_server/ && tar -xvzf ${GITHUB_SHA}.tar.gz"
    - name: Evaluate
      run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/id_rsa_eval cloud-user@23.111.106.99 "echo 'test' > test_file"
    - name: Copy results back
      run: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/id_rsa_eval cloud-user@23.111.106.99:~/test_file .
    - name: Metrics by Exam
      run: cat test_file
#    - name: Upload Artifacts to Storage
#      env:
#        DASH_SSH_KEY: ${{ secrets.DASH_SSH_KEY }}
#      run: |
#        echo "$DASH_SSH_KEY" > ~/id_rsa_dash
#        chmod 400 ~/id_rsa_dash
#        scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/id_rsa_dash client/reports/$(ls -1 client/reports/ | tail -n 1)/metrics_by_id.csv cloud-user@23.111.106.99:/home/cloud-user/shared/ai-journey-2019/scores_dir/$(git rev-parse HEAD | cut -c1-7).csv
